### PR TITLE
PDF exporting Functionality Added

### PR DESCRIPTION
**Pull request by swapadlinge**

### CODE REVIEW

**Review by VishalPhule — COMMENTED** [review]
Updated Code

**Comment by VishalPhule** [comment]
PDF exporting Functionality Added #1

**Review by mahi-28 — COMMENTED** [review]
Checked

**Review by mahi-28 — COMMENTED** [review]
Change accepted

**Comment by mahi-28** [comment]
Accepted

**Review by mahi-28 — COMMENTED** [review]
Change accepted

**Pull request merged**
